/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Artplayer: typeof import('./../components/Artplayer.vue')['default']
    AudioVisualizer: typeof import('./../components/Ui/AudioVisualizer.vue')['default']
    Aurora: typeof import('./../components/Background/Aurora.vue')['default']
    AuroraSettingsPanel: typeof import('./../components/Background/AuroraSettingsPanel.vue')['default']
    Button: typeof import('./../components/Ui/Button.vue')['default']
    ColorBends: typeof import('./../components/Background/ColorBends.vue')['default']
    ColorBendsSettingsPanel: typeof import('./../components/Background/ColorBendsSettingsPanel.vue')['default']
    GlassCheckbox: typeof import('./../components/Ui/GlassCheckbox.vue')['default']
    GlassSelect: typeof import('./../components/Ui/GlassSelect.vue')['default']
    HomeSkeleton: typeof import('./../components/HomeSkeleton.vue')['default']
    'IconIc:baselinePersonPin': typeof import('~icons/ic/baseline-person-pin')['default']
    LazyImage: typeof import('./../components/Ui/LazyImage.vue')['default']
    LocalMusicSettings: typeof import('./../components/Settings/LocalMusicSettings.vue')['default']
    LoginDialog: typeof import('./../components/Auth/LoginDialog.vue')['default']
    MiniPlayerMobile: typeof import('./../components/Mobile/MiniPlayerMobile.vue')['default']
    MobileDrawer: typeof import('./../components/Mobile/MobileDrawer.vue')['default']
    MobileHomeSkeleton: typeof import('./../components/MobileHomeSkeleton.vue')['default']
    MobileSongList: typeof import('./../components/Mobile/MobileSongList.vue')['default']
    MusicProgress: typeof import('./../components/Ui/MusicProgress.vue')['default']
    PageSkeleton: typeof import('./../components/PageSkeleton.vue')['default']
    Pagination: typeof import('./../components/Ui/Pagination.vue')['default']
    PlayerDrawer: typeof import('./../components/PlayerDrawer.vue')['default']
    PlayerDrawerMobile: typeof import('./../components/Mobile/PlayerDrawerMobile.vue')['default']
    PlaylistBubble: typeof import('./../components/Ui/PlaylistBubble.vue')['default']
    PlaylistCommentsPopup: typeof import('./../components/Mobile/PlaylistCommentsPopup.vue')['default']
    PlaylistDrawerMobile: typeof import('./../components/Mobile/PlaylistDrawerMobile.vue')['default']
    PlaylistInfoPopover: typeof import('./../components/Mobile/PlaylistInfoPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMVs: typeof import('./../components/Search/SearchMVs.vue')['default']
    SearchPlaylists: typeof import('./../components/Search/SearchPlaylists.vue')['default']
    SearchSongs: typeof import('./../components/Search/SearchSongs.vue')['default']
    SongCommentsDialog: typeof import('./../components/Comments/SongCommentsDialog.vue')['default']
    SongList: typeof import('./../components/SongList.vue')['default']
    TabGroup: typeof import('./../components/Ui/TabGroup.vue')['default']
    Ultimate: typeof import('./../components/Background/Ultimate.vue')['default']
    UltimateSettingsPanel: typeof import('./../components/Background/UltimateSettingsPanel.vue')['default']
    VolumeControl: typeof import('./../components/Ui/VolumeControl.vue')['default']
    VolumeControlMobile: typeof import('./../components/Mobile/VolumeControlMobile.vue')['default']
  }
}
