/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const LocalMusicDB: typeof import('../utils/indexedDB').LocalMusicDB
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const adaptColorForTheme: typeof import('../utils/colorThemeAdapter').adaptColorForTheme
  const adaptColorsForTheme: typeof import('../utils/colorThemeAdapter').adaptColorsForTheme
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createAudioVisualizer: typeof import('../utils/audioUtils').createAudioVisualizer
  const createPinia: typeof import('pinia').createPinia
  const crossfade: typeof import('../utils/audioUtils').crossfade
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const extractColorsFromImage: typeof import('../utils/colorExtractor').extractColorsFromImage
  const fadeVolume: typeof import('../utils/audioUtils').fadeVolume
  const formatCount: typeof import('../utils/time').formatCount
  const formatDate: typeof import('../utils/time').formatDate
  const formatDuration: typeof import('../utils/time').formatDuration
  const formatTime: typeof import('../utils/audioUtils').formatTime
  const generateGradientFromColor: typeof import('../utils/colorExtractor').generateGradientFromColor
  const getActivePinia: typeof import('pinia').getActivePinia
  const getAudioMetadata: typeof import('../utils/audioUtils').getAudioMetadata
  const getBrowserLang: typeof import('../utils/index').getBrowserLang
  const getColorPalette: typeof import('../utils/colorExtractor').getColorPalette
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFrequencyData: typeof import('../utils/audioUtils').getFrequencyData
  const h: typeof import('vue').h
  const httpGet: typeof import('../utils/http').httpGet
  const httpPost: typeof import('../utils/http').httpPost
  const httpUpload: typeof import('../utils/http').httpUpload
  const inject: typeof import('vue').inject
  const isDarkTheme: typeof import('../utils/colorThemeAdapter').isDarkTheme
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isSupportedAudioFormat: typeof import('../utils/audioUtils').isSupportedAudioFormat
  const localMusicDB: typeof import('../utils/indexedDB').localMusicDB
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseTime: typeof import('../utils/audioUtils').parseTime
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const rgbToHex: typeof import('../utils/colorExtractor').rgbToHex
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const testSongs: typeof import('../utils/testSongs').testSongs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useAudioStore: typeof import('../stores/modules/audio').useAudioStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useGlobalStore: typeof import('../stores/modules/global').useGlobalStore
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useLocalMusicStore: typeof import('../stores/modules/localMusic').useLocalMusicStore
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSettingsStore: typeof import('../stores/modules/settings').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUserStore: typeof import('../stores/modules/user').useUserStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AudioMetadata } from '../utils/audioUtils'
  import('../utils/audioUtils')
  // @ts-ignore
  export type { RGB, ColorPalette } from '../utils/colorExtractor'
  import('../utils/colorExtractor')
  // @ts-ignore
  export type { LocalMusicDB, LocalMusic } from '../utils/indexedDB'
  import('../utils/indexedDB')
  // @ts-ignore
  export type { AuroraSettingsState, ColorBendsSettingsState, UltimateSettingsState, FooterLyricsSettingsState, AudioVisualizerSettingsState, AudioQuality } from '../stores/modules/settings'
  import('../stores/modules/settings')
  // @ts-ignore
  export type { UserProfile } from '../stores/modules/user'
  import('../stores/modules/user')
}
